#!/bin/sh

### Environment ################################################################
MKTOOL=$(realpath $(dirname $0))
SOURCE=$(dirname $(dirname $(realpath $0)))
TARGET="build"
printf "[\e[36;1mTOOL\e[0m] Toolchain Builder\n"
printf "[\e[34;1mINFO\e[0m] Building from $SOURCE...\n"


### Workflow ###################################################################

function RAISE() {
    printf "fatal error occured"
    #rm -rf $TARGET
    exit 1
}

trap RAISE EXIT

### Dependencies ###############################################################
BUILDVER="grapic-1.2.95-Linux"
GRAPICLOCATION="https://perso.liris.cnrs.fr/alexandre.meyer/grapic/download/$BUILDVER.tgz"

source $MKTOOL/build-helpers

require make
require wget
require g++
require "libSDL2_ttf.so"
require "libSDL2_image*"

### Build #####################################################################

mkdir -p $MKTOOL/$TARGET && cd $MKTOOL/$TARGET

# download $GRAPICLOCATION

run "unpack $BUILDVER.tgz" tar xvzf $BUILDVER.tgz

cd $BUILDVER/src

run "compile the so" g++ -fPIC -shared Grapic.cpp -I . -I /usr/include/SDL2 -o $MKTOOL/$TARGET/libgrapic.so -L /usr/lib/ -l SDL2 -l SDL2_image -l SDL2_ttf

### We're done! ################################################################
trap - EXIT

printf "[\e[36;1mTOOL\e[0m] Toolchain built!\n"
